{% set name = "debuglater" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/debuglater-{{ version }}.tar.gz
  sha256: e99116a52b3b1515d8734ab7f26a74bb0f32f23d76b323792a9eb60714ab169e

build:
  entry_points:
    - debuglater=debuglater.cli:main
    - dltr=debuglater.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorama
    - python >=3.6

test:
  imports:
    - debuglater
  commands:
    - pip check
    - debuglater --help
    - dltr --help
  requires:
    - pip

about:
  home: https://github.com/ploomber/debuglater
  summary: Post-mortem debugging for Python programs
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - edublancas
